### ISSUE TITLE
ToDo List:

### ISSUE THREAD

**Issue by cphrmky** [IBM-Bluemix/ziggy#1]
- [x] Provision Cloudant database[s] - @cphrmky
- [x] Capture Bowie lyrics and store in DB - @cphrmky
- [x] Scrape the lyrics from [azlyrics](http://www.azlyrics.com/lyrics/davidbowie/) using `beautifulsoup` - @cphrmky
- [x] Sort albums into pre-defined personas `['Ziggy Stardust' , 'Alladin Sane', 'Modern Love', 'Lazarus', 'Earthling']`  - [Bowie discography](https://en.wikipedia.org/wiki/David_Bowie_discography)
- [x] Run `PersonalityInsights` against each persona and it's albums.
- [ ] Bonus use Tone Analyzer [https://tone-analyzer-demo.mybluemix.net/](https://tone-analyzer-demo.mybluemix.net/) on individual tracks.
- [ ] In time for SXSW fork the Celeb Match demo and map users into one of the Bowie personas.
